### ISSUE TITLE
Transparent (implicit) support for different technologies and tooling

### ISSUE THREAD

**Issue by sodic** [wasp-lang/wasp#1074]
This is a very abstract and way-into-the-future idea, but what if Wasp could be used like this (I'll adapt the current syntax for simplicity purposes):
```css
query getFoo {
  fn: getFoo in "foo.py"
  entities: [Foo]
}

query getBar {
  fn: getBar in "bar.ts"
  entities: [Bar]
}

action mergeFooAndBar {
  fn: merge in "merge.rs"
  entities: [Foo, Bar]
}
```
Users declare their operations on a high level and write the implementations in any language they Want.

Wasp would ensure to install whatever's necessary to execute what the users need. It would also take care of all the necessary plumbing required for different runtimes to communicate with each other (e.g., RPCs, message queues, etc.).

This idea can extend beyond operations.
