### ISSUE TITLE
wrong deploy path in netlify.toml file

### ISSUE THREAD

**Issue by vincanger** [wasp-lang/wasp#1948]
A [user reported an issue deploying to Netlify](https://discord.com/channels/686873244791210014/1227848613749592105/1227924703394660365) and I was able to recreate it with a fresh app. 

wasp v0.13.1
netlify-cli/17.22.1

When trying to deploy the client to netlify it looks in the root of the project for the build folder rather than from `.wasp/build/web-app` 

```sh
Adding local .netlify folder to .gitignore file...

Deploy path:        /Users/vincecanger/Documents/WASP/test/build
Configuration path: /Users/vincecanger/Documents/WASP/test/.wasp/build/web-app/netlify.toml
 ›   Error: The deploy directory "/Users/vincecanger/Documents/WASP/test/build" has not been found. Did you forget to run 'netlify build'?
web-app % 
```

to fix it, I had to change the deploy path in the toml file from:

```toml
[build]
  publish = "build/"
```

to this:
```toml
[build]
  publish = ".wasp/build/web-app/build/"
  ```
