### ISSUE TITLE
Consider offering managed development database

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#218]
I discussed this a lot here: https://github.com/wasp-lang/wasp/issues/173#issuecomment-815238435https://github.com/wasp-lang/wasp/issues/173#issuecomment-815238435 -> the main idea is that we could have Wasp manage the development database completely, so users don't have to think about it at all. This is all about the ease of usage and DX.

**Comment by Martinsos** [comment]
This doesn't mean we have to manage it completely and hide details for them -> instead, it could mean that we give them docker-compose.yaml file that will run it for them, so they don't have to remember that docker command!

This is how @Fecony wrote a docker-compose for his Wasp app:
```yaml
version: '3.8'
services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
```
