### ISSUE TITLE
Add support for a client setup function

### ISSUE THREAD

**Issue by sodic** [wasp-lang/wasp#593]
We want to support a client setup function in Wasp files. The interface should match the currently existing server setup function:
```css
app todoApp {
  title: "ToDo App",
  ...
  server: {
    setupFn: import setup from "@ext/serverSetup.js"
  }
  // This is new
  client: {
    setupFn: import setup from "@ext/clientSetup.js"
  }
}
```
