### ISSUE TITLE
Implement different types for SeverImport and ClientImport

### ISSUE THREAD

**Issue by sodic** [wasp-lang/wasp#810]
After merging #753, we require Wasp users to specify whether they're using a symbol in the server runtime or the the browser runtime:
```css
// Queries are executed on the server:
query getFoo {
    fn: import getFoo from "@server/queries.js"
}

// ...

// Pages are executed on the client:
page barPage {
    component: import Bar from "@client/components.js"
}
```
This is also specified in our docs.

However, we're still treating these two imports as a single type under the hood - `ExtImport`. Therefore, it doesn't matter whether a user imports something using `@client` or `@server`. The import will always work and resolve correctly (to the `src/client` and `src/server` folders respectively).

We need to fix this by implementing two different types, `ServerImport` and `ClientImport`, allowing the Wasp compiler (as well as VS Code) to warn users when they're importing something from the wrong runtime. There's no need to update the docs - they already claim this is the case :)
