### ISSUE TITLE
Reconsider Query and Action syntax

### ISSUE THREAD

**Issue by sodic** [wasp-lang/wasp#903]
Some parts of our syntax are weird and unintuitive. One of the more obvious culprits are Query definitions and Action definitions:

They have a lot of boilerplate:
```css
query getFoos {
  fn: import { getFoos } from “@server/queries.js”,
  entities: [Foo, Bar]
}

action makeFoo {
  fn: import { makeFoo } from “@server/foo/actions.js”,
  entities: [Foo]
}
```
We could reduce them to something like this:
```css
query getFoos
  function: getFoos
  file: "queries.js" 
  entities: Foo, Bar

query makeFoo
  function: makeFoo
  file: "foo/actions.js" 
  entities: Foo
```
Or, if we don't want to be too radical:
```css
query getFoos {
  function: getFoos
  file: "queries.js" 
  entities: [Foo, Bar]
}

query makeFoo {
  function: makeFoo
  file: "foo/actions.js" 
  entities: [Foo]
}
```
Anyway, we should discuss this.
